name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Debug secrets (no values printed, just checks existence)
      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then echo "❌ DOCKERHUB_USERNAME missing"; else echo "✅ DOCKERHUB_USERNAME found"; fi
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then echo "❌ DOCKERHUB_TOKEN missing"; else echo "✅ DOCKERHUB_TOKEN found"; fi

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-microservice:latest

      # Step 6: Deploy to Kubernetes (optional for now)
      - name: Deploy to Kubernetes
        run: |
          echo "Here we would run: kubectl apply -f k8s/"
          echo "Skipping actual cluster deployment for now..."
